### PR TITLE
Complete the refactoring of VimEditorUtils

### LINKED ISSUE #2905: Better separate VimTestUtils and VimEditorHost
The intent of these two projects was:

- `VimEditorHost`: provide a simple API for hosting `IVim` and `ITextBuffer` for testing and debugging purposes 
- `VimTestUtils`: provide xUnit helpers necessary for testing. Most notably the `StaFramework` infrastructure 

The intent though wasn't 100% clear when I created these years ago and accordingly I didn't break up the code correctly when I did this. As a result there is presently a lot of code in `VimTestUtils` that should be in `VimEditorHost`: lots of exports, extension methods for `VimCore`, etc ... 

This was okay before the move to shared projects because it was setup such that `VimTestUtils` could reference `VimEditorHost` and every test project referenced both of them. Now in shared projects (#2900) `VimEditorHost` has moved to a shared project and that breaks this relationship. As a result `VimTestUtils` needs to compile independently. That has really shined a light on the problems I created when I didn't separate the code cleanly. 

It's all working now but it was rough to work with (particularly makes creating `CompositionContainer` hard to reason about). This issue is meant to track cleaning that all up.

### PR DESCRIPTION
**Pull request by jaredpar**
The bulk of this change is simply moving code from `VimTestUtils` to `VimEditorHost` and cleaning up the resulting namespace changes. The actual semantic changes involved here are the following:

1. **Vastly** simplify how MEF works in the unit tests. The `VimEditorHost` type now just uses all exports from all assemblies by default except for a small subset of types that directly impact testing.  That also means we are more closely testing what we are shipping because all `Export` are included by default. This actually did end up finding a few small bugs in the code that needed to be fixed.
2. Fixed a couple small bugs that were exposed by the more comprehensive testing that now occurs. 
3. Changed `VimTestUtils` such that it no longer depends on any of the vim functionality. It is now simply just an xUnit helper library. This better sets us up to take on #2907. 

closes #2905

### CODE REVIEW

**Comment by jaredpar** [comment]
Note: this should be the last of the giant PRs that result from moving to shared projects. From here on out everything should be more manageable item by item PRs.

**Comment by nosami** [comment]
I am seeing some MEF composition errors when running this branch. I didn't test any of your other giant PRs but I am assuming the errors came from this one.

VsVim is also failing to initialize on Mac at least. I haven't investigated why yet but can take a look tonight or tomorrow. I am guessing that these composition errors are related.

```
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.VimWordCompletionSessionFactoryService.ctor(_wordCompletionSessionFactory): expected exactly 1 export matching constraints:
    Contract name: Vim.IWordCompletionSessionFactory
    TypeIdentityName: Vim.IWordCompletionSessionFactory
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.VimBufferFactory.ctor(_wordCompletionSessionFactoryService): expected exactly 1 export matching constraints:
    Contract name: Vim.IWordCompletionSessionFactoryService
    TypeIdentityName: Vim.IWordCompletionSessionFactoryService
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.VimImpl.ctor(bufferFactoryService): expected exactly 1 export matching constraints:
    Contract name: Vim.IVimBufferFactory
    TypeIdentityName: Vim.IVimBufferFactory
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.ChangeTracker.ctor(_vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.UI.Cocoa.Implementation.RelativeLineNumbers.RelativeLineNumbersMarginFactory.ctor(vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.AutoCommandRunner.ctor(_vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: VimHost.DefaultKeyProcessorProvider.ctor(vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.IncrementalSearchTaggerProvider.ctor(_vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.HighlightIncrementalSearchTaggerProvider.ctor(_vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.SubstituteConfirmTaggerProvider.ctor(_vim): expected exactly 1 export matching constraints:
    Contract name: Vim.IVim
    TypeIdentityName: Vim.IVim
but found 0.
```

**Comment by jaredpar** [comment]
> I am seeing some MEF composition errors when running this branch.

What context are you seeing this in? I tested `VimApp` a few times through this PR to make sure everything was still working. But I only tested the VS2019 configuration. Will try out a few others later today when I'm on my desktop. 

> INFO [2021-07-12 11:40:59Z]: MEF composition error: Vim.VimWordCompletionSessionFactoryService.ctor(_wordCompletionSessionFactory): expected exactly 1 export matching constraints:
    Contract name: Vim.IWordCompletionSessionFactory
    TypeIdentityName: Vim.IWordCompletionSessionFactory
but found 0.

Reading through the rest of the errors that does seem like the root cause. 

Actually ... thinking through this I may know what the problem is if you're seeing the composition error in Mac. This was previously a part of the `IVimSpecificService` layer and hence was tolerant to missing MEF components. Now it's required and I didn't think to check to see if the Mac layer exported that interface. If Mac doesn't export that then that is likely the problem.

If so easy fix and sorry for not thinking through that part 😦

**Comment by jaredpar** [comment]
Yeah that appears to be the problem. Will submit a patch in a little bit here.

**Comment by jaredpar** [comment]
@nosami pushed a fix that should take care of the composition error that you were seeing. I also added a stop gap test that should help prevent issues like this in the future. It attempts to simulate how we build up a Mac composition inside of our Windows tests. It's not perfect but it should help serve as a stop gap until we get #2907 implemented.

**Review by nosami — APPROVED** [review]
It's working great now on Mac.

**Comment by nosami** [comment]
> If so easy fix and sorry for not thinking through that part

No need to be sorry, easy mistake - I'm just grateful that I can use this code at all :)

**Pull request merged**
