### PR TITLE
Fix the link

### PR DESCRIPTION
**Pull request by TKumadaki**
Because VsVim moved to the organization,I correct the link.
Even in the present situation it will be redirected correctly,
I corrected it just in case.
And the link below still seems to be a personal name.

[https://ci.appveyor.com/project/jaredpar/vsvim](https://ci.appveyor.com/project/jaredpar/vsvim)

### CODE REVIEW

**Comment by TKumadaki** [comment]
I noticed that I did not modify "README.ch.md".
However, it seems that appveyor is not working properly now.
#2510
I will try to commit after appveyor is normal.

**Comment by jaredpar** [comment]
Close / Reopen to validate that AppVeyor is fixed. Looks like it is as a bulid was kicked off for this PR.

**Comment by TKumadaki** [comment]
@jaredpar
Should I send the next commit?
Or I can close this PR and send it as another PR.

**Comment by jaredpar** [comment]
Pretty sure I fixed it this time. Validating my change with #2511. One more close / open to trigger the update here.

**Comment by ricksladkey** [comment]
PR build worked. Merging to see if master builds.

**Pull request merged**
