### PR TITLE
Strong name the assemblies.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Use DebugType portable.
Use LangVersion "latest" (lowercase) as F# compiler doesn't accept Latest with uppercase.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Let me know if you'd like to roll back to DebugType full or should we try portable again and see what breaks? 

Would be nice to move to portable eventually and uncover infrastructure that doesn't support it properly.

**Comment by jaredpar** [comment]
The DebugType change is fine. The current state was due to a build break at some point in the past. I can't remember the details of it unfortunately. 

I'm going to merge this once I release 2.8 (this week).

**Comment by KirillOsenkov** [comment]
There's a test failure around Mocks and ref emit that is most likely due to the assemblies now being signed.

I didn't get a chance to look into it yet, but was going to soon. You might want to hold off merging until we get a green build.

```
Running unit tests
VsVimTestn\net472\VsVim.UnitTest.dll
xUnit.net Console Runner v2.4.1 (32-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: Vim.Core.UnitTest
  Discovered:  Vim.Core.UnitTest
  Starting:    Vim.Core.UnitTest
    Vim.UnitTest.VimTest+MiscTest.GetOrCreateVimTextBuffer_Cache [FAIL]
      System.ArgumentException : Type to mock must be an interface or an abstract or non-sealed class. 
      ---- System.TypeLoadException : Type 'Castle.Proxies.ObjectProxy_57' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' is attempting to implement an inaccessible interface.
      Stack Trace:
           at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
           at Moq.Mock`1.<InitializeInstance>b__24_0()
           at Moq.PexProtector.Invoke(Action action)
           at Moq.Mock`1.InitializeInstance()
           at Moq.Mock`1.OnGetObject()
           at Moq.Mock.GetObject()
           at Moq.Mock.get_Object()
           at Moq.Mock`1.get_Object()
        Test\VimCoreTest\VimTest.cs(80,0): at Vim.UnitTest.VimTest.CreateVim()
        Test\VimCoreTest\VimTest.cs(69,0): at Vim.UnitTest.VimTest..ctor(Boolean createVim)
           at Vim.UnitTest.VimTest.MiscTest..ctor()
        ----- Inner Stack Trace -----
           at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
           at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
           at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
           at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type)
           at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1.<GenerateCode>b__0(String n, INamingScope s)
           at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
           at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
           at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
           at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
           at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
    Vim.UnitTest.VimTest+MiscTest.RemoveBuffer_AssociatedTextView [FAIL]
      System.ArgumentException : Type to mock must be an interface or an abstract or non-sealed class. 
```

**Comment by KirillOsenkov** [comment]
Let's close this for now and I can reopen and fix it up if I ever come back to this again.

**Pull request closed without merging**
